# -*- coding: utf-8 -*-
"""training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11h8AxRl-SEqVLCAPIYII1Fy33KJuK6eL
"""

def api ():
  search_no = get_search_no()
  if not search_no: 
    Logger.get().warn("search_no doesn't exsist.")
    return None, "error"
  else:
    try:
      result = special_execute_somrthing(search_no)
      return result, None
    except: 
      Logger.get().exception("oh my god")

for i in range(10):
  print(i)

for i in range(100):
  print(i)

my_life = 5
while my_life:
  my_life -=1
  print(my_life)

for item in ["a","b","c"]:
  print (item)

idx = 4
while True:
  if idx > 5:
    break
  idx +=1
  print (idx)

my_name = "mana"
age = 26
is_good = True
unittest = 1

print (my_name)

print (age)

my_name + age

my_name + str(age)

type(my_name)

type(age)

# str is the variables having text information
# int is integer and the type of variable including numbers

users = [
         "Yo", "ken", "Nao", "Shin", "Lee"
]

users.append("Miu")
users.remove("Nao")

users[0]
users[0:2]
users[1:]
users[::2]
users[::-1]

users[0::]
users[:1]
users[2:]
users[3:]
users[4]

# index access is not clear to me yet

users = ["Yo", "ken", "Nao", "Shin", "Lee"]
users =[u.lower() for u in users if u.find("e") !=-1]

user_dict = {"Yohei": 30, "Jhon": 50}

for k, v in user_dict.items():
  print (k, v)

# Key and value are represented as K and V as short

user_dict["Yohei"]
user_dict.get("Nao", 20)

user_dict["Yohei"]=31
del user_dict["Jhon"]

print(user_dict)

set_ = {
    "Tennis", "Ramen",
    "Programminig"
}

set_.add("Gs")
set_.remove("Ramen")

users = [
         "Yo", "ken", "Nao", "Shin", "Lee"
]

users[0]

users = [
         "Yo", "ken", "Nao", "Shin", "Lee"
]

users = [
         "Yo", "ken", "Nao", "Shin", "Lee"
]

users[0:2]

users[1:]

users[0:]

# 0: means getting all info in the []

users [::-1]

# ::-1は逆向きに一覧出す

users[:-1]

users[0::]

users[0:3]

users[1:4]

users[1:]

users[::2]

users[::3]

users = ["Yo", "ken", "Nao", "Shin", "Lee"]
users =[u.lower() for u in users if u.find("e") !=-1]
print(users)

# u is new variable defined in for function. 
# u="Yo" and the rest of names in the users variables
# u.lower=making u lower case
# u.find("e")= finding "e" out of u

